# Generated by Django 4.2.3 on 2023-11-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_ipaddress_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
