# Generated by Django 4.2.3 on 2023-11-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_remove_article_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleHits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_module.article', verbose_name='مقالات')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_module.ipaddress', verbose_name='آی پی')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(related_name='hits', through='article_module.ArticleHits', to='article_module.ipaddress', verbose_name='بازدید ها'),
        ),
    ]
