# Generated by Django 4.2.3 on 2023-11-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0004_articlehits_article_hits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-create_date'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, default='0', max_length=400, verbose_name='Title in URL'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, default='0', max_length=400, verbose_name='Title in URL'),
        ),
        migrations.AddField(
            model_name='article',
            name='text_en',
            field=models.TextField(default='0', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='article',
            name='text_fa',
            field=models.TextField(default='0', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(default='0', max_length=200, verbose_name='Article Title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fa',
            field=models.CharField(default='0', max_length=200, verbose_name='Article Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='images/articles', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='selected_categories',
            field=models.ManyToManyField(to='article_module.articlecategory', verbose_name='Categories'),
        ),
    ]
