# Generated by Django 4.2.3 on 2023-11-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0006_rename_text_en_article_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slug_en',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug_fa',
        ),
    ]
